name: Copy to Iderma Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout server repository
        uses: actions/checkout@v4
        with:
          repository: IdermaCapilar1/server
          token: ${{ secrets.PMA_TOKEN }}
          path: server

      - name: Clone Iderma Docker repository
        run: |
          git clone https://github.com/IdermaCapilar1/iderma-docker.git
          cd iderma-docker
          git config user.name "tu_usuario"
          git config user.email "tu_email"

      - name: Copy files
        run: |
          cp -R server/* iderma-docker/backend/

      - name: Commit and push changes
        run: |
          cd iderma-docker
          git add .
          git commit -m "Actualización desde el repositorio server"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PMA_TOKEN }}
