name: Actualizar archivos en VPS

on:
  push:
    branches:
      - main

jobs:
  update-server:
    runs-on: self-hosted
    steps:
      - name: Marcar directorio como seguro
        run: |
          git config --global --add safe.directory /root/server
      
      - name: Actualizar repositorio server
        run: |
          cd /root/server
          git pull origin main

      - name: Copiar archivos actualizados
        run: |
          rsync -av /root/server/ /root/iderma-docker/backend/
